interface Sentence {
  time: number;
  text: string;
  question: boolean;
  posibilities: string[] | undefined;
}

export const BlindingLightsLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 14,
    text: "Yeah",
    question: false,
    posibilities: undefined,
  },
  {
    time: 28,
    text: "I've been tryna call",
    question: false,
    posibilities: undefined,
  },
  {
    time: 31,
    text: "I've been on my own for long enough",
    question: false,
    posibilities: undefined,
  },
  {
    time: 33,
    text: "Maybe you can _____ me how to love, maybe",
    question: false,
    posibilities: undefined,
  },
  {
    time: 38,
    text: "Maybe you can _____ me how to love, maybe",
    question: true,
    posibilities: ["SHOW", "SAW", "SHOP"],
  },
  {
    time: 39,
    text: "I'm going through withdrawals",
    question: false,
    posibilities: undefined,
  },
  {
    time: 42,
    text: "You don't even have to do too much",
    question: false,
    posibilities: undefined,
  },
  {
    time: 45,
    text: "You can turn me on with just a touch, baby",
    question: false,
    posibilities: undefined,
  },
  {
    time: 50,
    text: "I _____ around and",
    question: false,
    posibilities: undefined,
  },
  {
    time: 51,
    text: "I _____ around and",
    question: true,
    posibilities: ["LOOK", "TOOK", "BOOK"],
  },
  {
    time: 52,
    text: "Sin City's cold and empty (Oh)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 54,
    text: "No one's around to judge me (Oh)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 57,
    text: "I can't see clearly when you're gone",
    question: false,
    posibilities: undefined,
  },
  {
    time: 61,
    text: "I said, ooh, I'm blinded by the lights",
    question: false,
    posibilities: undefined,
  },
  {
    time: 67,
    text: "No, I can't sleep until I feel your touch",
    question: false,
    posibilities: undefined,
  },
  {
    time: 73,
    text: "I said, ooh, I'm drowning in the night",
    question: false,
    posibilities: undefined,
  },
  {
    time: 78,
    text: "Oh, when I'm like this, you're the _____ I trust",
    question: false,
    posibilities: undefined,
  },
  {
    time: 82,
    text: "Oh, when I'm like this, you're the _____ I trust",
    question: true,
    posibilities: ["ONE", "WON", "MAN"],
  },
  {
    time: 83,
    text: "Hey, hey, hey",
    question: false,
    posibilities: undefined,
  },
  {
    time: 95,
    text: "I'm running out of time",
    question: false,
    posibilities: undefined,
  },
  {
    time: 98,
    text: "'Cause I can see the sun light up the sky",
    question: false,
    posibilities: undefined,
  },
  {
    time: 101,
    text: "So I hit the road in overdrive, baby, oh",
    question: false,
    posibilities: undefined,
  },
  {
    time: 107,
    text: "The city's cold and empty (Oh)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 110,
    text: "No one's around to judge me (Oh)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 113,
    text: "I can't _____ clearly when you're gone",
    question: false,
    posibilities: undefined,
  },
  {
    time: 116,
    text: "I can't _____ clearly when you're gone",
    question: true,
    posibilities: ["SEE", "SEA", "SHINK"],
  },
  {
    time: 117,
    text: "I said, ooh, I'm blinded by the lights",
    question: false,
    posibilities: undefined,
  },
  {
    time: 123,
    text: "No, I can't sleep until I feel your touch",
    question: false,
    posibilities: undefined,
  },
  {
    time: 129,
    text: "I said, ooh, I'm drowning in the night",
    question: false,
    posibilities: undefined,
  },
  {
    time: 135,
    text: "Oh, when I'm like this, you're the one I trust",
    question: false,
    posibilities: undefined,
  },
  {
    time: 140,
    text: "I'm just calling back to let you know (Back to let you know)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 143,
    text: "I could never say it on the phone (Say it on the phone)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 146,
    text: "Will never let you go this _____ (Ooh)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 150,
    text: "Will never let you go this _____ (Ooh)",
    question: true,
    posibilities: ["TIME", "MINE", "KIND"],
  },
  {
    time: 151,
    text: "I said, ooh, I'm blinded by the lights",
    question: false,
    posibilities: undefined,
  },
  {
    time: 157,
    text: "No, I can't sleep until I feel your touch",
    question: false,
    posibilities: undefined,
  },
  {
    time: 162,
    text: "Hey, hey, hey",
    question: false,
    posibilities: undefined,
  },
  {
    time: 163,
    text: "Hey, hey, hey",
    question: false,
    posibilities: undefined,
  },
  {
    time: 185,
    text: "I said, ooh, I'm blinded by the lights",
    question: false,
    posibilities: undefined,
  },
  {
    time: 191,
    text: "No, I can't sleep until I feel your _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 193,
    text: "No, I can't sleep until I feel your _____",
    question: true,
    posibilities: ["TOUCH", "CATCH", "MUCH"],
  },
];

export const EnemyLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 36,
    text: "Look out for yourself",
    question: false,
    posibilities: undefined,
  },
  {
    time: 38,
    text: "I wake up to the sounds of the _____ that allows",
    question: false,
    posibilities: undefined,
  },
  {
    time: 41,
    text: "I wake up to the sounds of the _____ that allows",
    question: true,
    posibilities: ["SILENCE", "LICENSE", "VALENCE"],
  },
  {
    time: 42,
    text: "For my mind to run around, with my ear up to the ground",
    question: false,
    posibilities: undefined,
  },
  {
    time: 45,
    text: "I'm searching to behold the stories that are told",
    question: false,
    posibilities: undefined,
  },
  {
    time: 48,
    text: "When my back is to the world that was smiling when I turned",
    question: false,
    posibilities: undefined,
  },
  {
    time: 54,
    text: "Tell you, you're the greatest",
    question: false,
    posibilities: undefined,
  },
  {
    time: 58,
    text: "But once you _____, they hate us",
    question: false,
    posibilities: undefined,
  },
  {
    time: 64,
    text: "But once you _____, they hate us",
    question: true,
    posibilities: ["TURN", "BURN", "URN"],
  },
  {
    time: 65,
    text: "Oh, the misery",
    question: false,
    posibilities: undefined,
  },
  {
    time: 67,
    text: "Everybody wants to be my enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 71,
    text: "_____ the sympathy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 72,
    text: "_____ the sympathy",
    question: true,
    posibilities: ["SPARE", "SPURS", "DESPAIR"],
  },
  {
    time: 73,
    text: "Everybody wants to be my enemy-y-y-y-y",
    question: false,
    posibilities: undefined,
  },
  {
    time: 80,
    text: "(Look out for yourself)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 82,
    text: "My enemy-y-y-y-y",
    question: false,
    posibilities: undefined,
  },
  {
    time: 86,
    text: "(Look out for yourself)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 88,
    text: "But I'm ready",
    question: false,
    posibilities: undefined,
  },
  {
    time: 89,
    text: "Your words up on the wall as you're prayin' for my _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 91,
    text: "Your words up on the wall as you're prayin' for my _____",
    question: true,
    posibilities: ["FALL", "FOOL", "FOLD"],
  },
  {
    time: 92,
    text: "And the laughter in the halls and the names that I've been called",
    question: false,
    posibilities: undefined,
  },
  {
    time: 95,
    text: "I stack it in my mind, and I'm waiting for the time",
    question: false,
    posibilities: undefined,
  },
  {
    time: 98,
    text: "When I show you what it's like to be words spit in a mic",
    question: false,
    posibilities: undefined,
  },
  {
    time: 101,
    text: "Tell you, you're the greatest",
    question: false,
    posibilities: undefined,
  },
  {
    time: 107,
    text: "But once you turn, they hate us (Ha)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 114,
    text: "Oh, the misery",
    question: false,
    posibilities: undefined,
  },
  {
    time: 117,
    text: "Everybody wants to be my enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 121,
    text: "Spare the sympathy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 123,
    text: "Everybody wants to be my enemy-y-y-y-y",
    question: false,
    posibilities: undefined,
  },
  {
    time: 129,
    text: "(Look out for yourself)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 132,
    text: "My enemy-y-y-y-y (Yeah)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 136,
    text: "(Look out for yourself)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 137,
    text: "Uh, look, okay",
    question: false,
    posibilities: undefined,
  },
  {
    time: 138,
    text: "I'm hoping that somebody pray for me",
    question: false,
    posibilities: undefined,
  },
  {
    time: 140,
    text: "I'm praying that somebody _____ for me",
    question: false,
    posibilities: undefined,
  },
  {
    time: 141,
    text: "I'm praying that somebody _____ for me",
    question: true,
    posibilities: ["HOPE", "HOLE", "HOT"],
  },
  {
    time: 142,
    text: "I'm staying where nobody 'posed to be",
    question: false,
    posibilities: undefined,
  },
  {
    time: 143,
    text: "P-P-Posted, being a wreck of emotions",
    question: false,
    posibilities: undefined,
  },
  {
    time: 145,
    text: "Ready to go whenever, just let me know",
    question: false,
    posibilities: undefined,
  },
  {
    time: 146,
    text: "The road is long, so put the pedal into the floor",
    question: false,
    posibilities: undefined,
  },
  {
    time: 148,
    text: "The enemy on my trail, my energy unavailable",
    question: false,
    posibilities: undefined,
  },
  {
    time: 150,
    text: "I'ma tell 'em hasta luego",
    question: false,
    posibilities: undefined,
  },
  {
    time: 152,
    text: "I know they wanna plot on my trot to the top",
    question: false,
    posibilities: undefined,
  },
  {
    time: 153,
    text: "I've been outta _____, thinkin' out the box",
    question: false,
    posibilities: undefined,
  },
  {
    time: 153,
    text: "I've been outta _____, thinkin' out the box",
    question: true,
    posibilities: ["SHAPE", "SHAKE", "SHAME"],
  },
  {
    time: 154,
    text: "I'm an astronaut, I blasted off the planet rock to cause catastrophe",
    question: false,
    posibilities: undefined,
  },
  {
    time: 156,
    text: "IAnd it matters more because I had it not",
    question: false,
    posibilities: undefined,
  },
  {
    time: 158,
    text: "Had I thought about wreaking havoc on",
    question: false,
    posibilities: undefined,
  },
  {
    time: 160,
    text: "An opposition, kinda shocking",
    question: false,
    posibilities: undefined,
  },
  {
    time: 161,
    text: "They want a static with precision, I'm automatic quarterback",
    question: false,
    posibilities: undefined,
  },
  {
    time: 163,
    text: "I ain't talkin' sacking, _____ it",
    question: false,
    posibilities: undefined,
  },
  {
    time: 164,
    text: "I ain't talkin' sacking, _____ it",
    question: true,
    posibilities: ["PACK", "BACK", "LACK"],
  },
  {
    time: 165,
    text: "Pack it up, I don't panic, better batter up",
    question: false,
    posibilities: undefined,
  },
  {
    time: 166,
    text: "Who the baddest? It don't matter 'cause we at ya throat",
    question: false,
    posibilities: undefined,
  },
  {
    time: 167,
    text: "Everybody wants to be my enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 170,
    text: "Spare the sympathy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 173,
    text: "Everybody wants to be my enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 177,
    text: "Oh, the misery",
    question: false,
    posibilities: undefined,
  },
  {
    time: 179,
    text: "Everybody wants to be my enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 183,
    text: "Spare the sympathy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 185,
    text: "Everybody wants to be my enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 188,
    text: "Pray it away, I swear, I'll never be a saint, no way",
    question: false,
    posibilities: undefined,
  },
  {
    time: 194,
    text: "My enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 195,
    text: "Pray it away, I swear, I'll never be a saint",
    question: false,
    posibilities: undefined,
  },
  {
    time: 198,
    text: "Look out for yourself",
    question: false,
    posibilities: undefined,
  },
  {
    time: 202,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
];

export const JinjerLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 12,
    text: "Step forward and _____ a new sunrise",
    question: false,
    posibilities: undefined,
  },
  {
    time: 18,
    text: "Step forward and _____ a new sunrise",
    question: true,
    posibilities: ["MEET", "MEAT", "MEAL"],
  },
  {
    time: 19,
    text: "A coward is shivering inside",
    question: false,
    posibilities: undefined,
  },
  {
    time: 25,
    text: "Today I'll be a friend of mine",
    question: false,
    posibilities: undefined,
  },
  {
    time: 31,
    text: "Who _____ suffering with smile",
    question: false,
    posibilities: undefined,
  },
  {
    time: 36,
    text: "Who _____ suffering with smile",
    question: true,
    posibilities: ["SWALLOWS", "FOLLOWS", "FALLOWS"],
  },
  {
    time: 37,
    text: "I drew a different reality",
    question: false,
    posibilities: undefined,
  },
  {
    time: 41,
    text: "With unconditional loyalty",
    question: false,
    posibilities: undefined,
  },
  {
    time: 47,
    text: "Ego hardly can be piqued 'cause I'm selfless",
    question: false,
    posibilities: undefined,
  },
  {
    time: 57,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 69,
    text: "Scale armour blaze",
    question: false,
    posibilities: undefined,
  },
  {
    time: 76,
    text: "Virgin innocence",
    question: false,
    posibilities: undefined,
  },
  {
    time: 79,
    text: "One being brings life",
    question: false,
    posibilities: undefined,
  },
  {
    time: 84,
    text: "Another _____ for death",
    question: false,
    posibilities: undefined,
  },
  {
    time: 87,
    text: "Another _____ for death",
    question: true,
    posibilities: ["RUNS", "GUNS", "TUNS"],
  },
  {
    time: 88,
    text: "Scale armour blaze",
    question: false,
    posibilities: undefined,
  },
  {
    time: 93,
    text: "Virgin innocence",
    question: false,
    posibilities: undefined,
  },
  {
    time: 97,
    text: "One being brings life",
    question: false,
    posibilities: undefined,
  },
  {
    time: 101,
    text: "Another runs for death",
    question: false,
    posibilities: undefined,
  },
  {
    time: 104,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 118,
    text: "_____ promises I ever give",
    question: false,
    posibilities: undefined,
  },
  {
    time: 122,
    text: "_____ promises I ever give",
    question: true,
    posibilities: ["NO", "KNOW", "NONE"],
  },
  {
    time: 123,
    text: "Don't rely on me and I won't deceive",
    question: false,
    posibilities: undefined,
  },
  {
    time: 130,
    text: "The beginning or the end, you can't tell",
    question: false,
    posibilities: undefined,
  },
  {
    time: 134,
    text: "When I wave my fin and shake my tail",
    question: false,
    posibilities: undefined,
  },
  {
    time: 142,
    text: "I grew in different normality",
    question: false,
    posibilities: undefined,
  },
  {
    time: 147,
    text: "With unblameable morality",
    question: false,
    posibilities: undefined,
  },
  {
    time: 152,
    text: "_____ and nets are there for men but I'm skittish",
    question: false,
    posibilities: undefined,
  },
  {
    time: 161,
    text: "_____ and nets are there for men but I'm skittish",
    question: true,
    posibilities: ["HOOKS", "HOCKS", "HOODS"],
  },
  {
    time: 162,
    text: "Scale armour blaze",
    question: false,
    posibilities: undefined,
  },
  {
    time: 168,
    text: "Virgin innocence",
    question: false,
    posibilities: undefined,
  },
  {
    time: 171,
    text: "One being brings life",
    question: false,
    posibilities: undefined,
  },
  {
    time: 176,
    text: "Another runs for death",
    question: false,
    posibilities: undefined,
  },
  {
    time: 180,
    text: "Scale armour blaze",
    question: false,
    posibilities: undefined,
  },
  {
    time: 185,
    text: "Virgin innocence",
    question: false,
    posibilities: undefined,
  },
  {
    time: 189,
    text: "One being brings life",
    question: false,
    posibilities: undefined,
  },
  {
    time: 193,
    text: "Another runs for death",
    question: false,
    posibilities: undefined,
  },
  {
    time: 200,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 211,
    text: "Neptune's child shivering inside",
    question: false,
    posibilities: undefined,
  },
  {
    time: 219,
    text: "Drowns in the liquid _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 232,
    text: "Drowns in the liquid _____",
    question: true,
    posibilities: ["GOLD", "GOAL", "GOAT"],
  },
  {
    time: 233,
    text: "Cherished his life to the underworld",
    question: false,
    posibilities: undefined,
  },
  {
    time: 246,
    text: "Meet me flashing when winter cries",
    question: false,
    posibilities: undefined,
  },
  {
    time: 255,
    text: "Pisces swimming through the river",
    question: false,
    posibilities: undefined,
  },
  {
    time: 258,
    text: "All their life against the stream",
    question: false,
    posibilities: undefined,
  },
  {
    time: 262,
    text: "Searching for a hook to catch on",
    question: false,
    posibilities: undefined,
  },
  {
    time: 265,
    text: "And see their sun _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 274,
    text: "And see their sun _____",
    question: true,
    posibilities: ["BEAM", "BEEN", "BEAT"],
  },
  {
    time: 275,
    text: "Then suffocate in painful tortures",
    question: false,
    posibilities: undefined,
  },
  {
    time: 279,
    text: "On cutting tables of callous men",
    question: false,
    posibilities: undefined,
  },
  {
    time: 283,
    text: "Under a knife of handsome butchers",
    question: false,
    posibilities: undefined,
  },
  {
    time: 286,
    text: "Emeralds are ripped away",
    question: false,
    posibilities: undefined,
  },
  {
    time: 289,
    text: "Emeralds are ripped away",
    question: false,
    posibilities: undefined,
  },
  {
    time: 293,
    text: "Emeralds are ripped away",
    question: false,
    posibilities: undefined,
  },
  {
    time: 296,
    text: "Emeralds are ripped away",
    question: false,
    posibilities: undefined,
  },
];

export const LazyTownLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 8,
    text: "Robbie: “Are you, uh, a real villain?”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 10,
    text: "Bobbie: “Well, uh, technically... nah.”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 12,
    text: "Robbie: “Have you ever _____ a good guy, like, uh, like a real superhero?”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 15,
    text: "Robbie: “Have you ever _____ a good guy, like, uh, like a real superhero?”",
    question: true,
    posibilities: ["CAUGHT", "FOUGHT", "THOUGHT"],
  },
  {
    time: 16,
    text: "Bobbie: “Nah.”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 18,
    text: "Robbie: “Have you ever tried a disguise?”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 20,
    text: "Bobbie: “Nah, nah...”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 22,
    text: "Robbie: “_____! I can see that I will have to teach you how to be villains!”",
    question: false,
    posibilities: undefined,
  },
  {
    time: 33,
    text: "Robbie: “_____! I can see that I will have to teach you how to be villains!”",
    question: true,
    posibilities: ["ALRIGHT", "WRITE", "RIDE"],
  },
  {
    time: 34,
    text: "Hey!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 38,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 39,
    text: "Hey!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 44,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 46,
    text: "_____ listen closely:",
    question: false,
    posibilities: undefined,
  },
  {
    time: 48,
    text: "_____ listen closely:",
    question: true,
    posibilities: ["NOW", "KNOW", "NO"],
  },
  {
    time: 49,
    text: "Here's a little lesson in trickery",
    question: false,
    posibilities: undefined,
  },
  {
    time: 52,
    text: "This is going down in history",
    question: false,
    posibilities: undefined,
  },
  {
    time: 54,
    text: "If you wanna be a villain number one",
    question: false,
    posibilities: undefined,
  },
  {
    time: 58,
    text: "You have to _____ a superhero on the run",
    question: false,
    posibilities: undefined,
  },
  {
    time: 63,
    text: "You have to _____ a superhero on the run",
    question: true,
    posibilities: ["CHASE", "CHESS", "CHANCE"],
  },
  {
    time: 64,
    text: "Just follow my moves, and sneak around",
    question: false,
    posibilities: undefined,
  },
  {
    time: 67,
    text: "Be careful not to make a sound",
    question: false,
    posibilities: undefined,
  },
  {
    time: 69,
    text: "(Shh!)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 70,
    text: "(No, don't touch that!)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 77,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 78,
    text: "Hey!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 83,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 90,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 92,
    text: "Ha ha ha",
    question: false,
    posibilities: undefined,
  },
  {
    time: 93,
    text: "Now look at this net, that I just found",
    question: false,
    posibilities: undefined,
  },
  {
    time: 96,
    text: "When I say go, be ready to _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 98,
    text: "When I say go, be ready to _____",
    question: true,
    posibilities: ["THROW", "THREW", "THROUGH"],
  },
  {
    time: 99,
    text: "Go!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 101,
    text: "(Throw it at him, not me!)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 103,
    text: "(Ugh, let's try something else)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 105,
    text: "Now watch and learn, here's the _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 107,
    text: "Now watch and learn, here's the _____",
    question: true,
    posibilities: ["DEAL", "MEAL", "PEEL"],
  },
  {
    time: 108,
    text: "He'll slip and slide on this banana peel!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 111,
    text: "(Ha ha ha, *gasp*! What are you doing!?)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 115,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 127,
    text: "Ba-ba-biddly-ba-ba-ba-ba, ba-ba-ba-ba-ba-ba-ba",
    question: false,
    posibilities: undefined,
  },
  {
    time: 132,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 133,
    text: "Hey!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 133,
    text: "Ba-ba-biddly-ba-ba-ba-ba, ba-ba-ba-ba-ba-ba-ba",
    question: false,
    posibilities: undefined,
  },
  {
    time: 138,
    text: "Villain Number One!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 151,
    text: "Ba-ba-biddly-ba-ba-ba-ba, ba-ba-ba-ba-ba-ba-ba",
    question: false,
    posibilities: undefined,
  },
  {
    time: 156,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 157,
    text: "Hey!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 158,
    text: "Ba-ba-biddly-ba-ba-ba-ba, ba-ba-ba-ba-ba-ba-ba",
    question: false,
    posibilities: undefined,
  },
  {
    time: 162,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 163,
    text: "We are Number One",
    question: false,
    posibilities: undefined,
  },
  {
    time: 165,
    text: "We are Number One, hey hey!",
    question: false,
    posibilities: undefined,
  },
];

export const MyConfessionLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 27,
    text: "Give me a _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 29,
    text: "Give me a _____",
    question: true,
    posibilities: ["SIGN", "SITE", "SIGHT"],
  },
  {
    time: 30,
    text: "Sing the words of innocence and broken pride",
    question: false,
    posibilities: undefined,
  },
  {
    time: 36,
    text: "Make my conclusions fail",
    question: false,
    posibilities: undefined,
  },
  {
    time: 41,
    text: "Send me a sign, heal this broken melody",
    question: false,
    posibilities: undefined,
  },
  {
    time: 45,
    text: "'Cause each night I die in _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 50,
    text: "'Cause each night I die in _____",
    question: true,
    posibilities: ["HELL", "HEALTH", "HELM"],
  },
  {
    time: 51,
    text: "My god has shown his sympathy for all the spirits lost",
    question: false,
    posibilities: undefined,
  },
  {
    time: 57,
    text: "I'll prayed for salvation and peace for ages",
    question: false,
    posibilities: undefined,
  },
  {
    time: 64,
    text: "Standing in the summer breeze, inhaling life again",
    question: false,
    posibilities: undefined,
  },
  {
    time: 70,
    text: "A new day has come",
    question: false,
    posibilities: undefined,
  },
  {
    time: 73,
    text: "A chance to _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 75,
    text: "A chance to _____",
    question: true,
    posibilities: ["RELIVE", "RELIEVE", "BELIEVE"],
  },
  {
    time: 76,
    text: "Forget and forgive",
    question: false,
    posibilities: undefined,
  },
  {
    time: 85,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 94,
    text: "Somehow I wasted all",
    question: false,
    posibilities: undefined,
  },
  {
    time: 97,
    text: "They sealed my voice and wisdom",
    question: false,
    posibilities: undefined,
  },
  {
    time: 100,
    text: "But my _____ was born on the battleground",
    question: false,
    posibilities: undefined,
  },
  {
    time: 106,
    text: "But my _____ was born on the battleground",
    question: true,
    posibilities: ["SOUL", "SOUR", "SOUGHT"],
  },
  {
    time: 107,
    text: "Justice in blood... long awaited victory",
    question: false,
    posibilities: undefined,
  },
  {
    time: 113,
    text: "And tonight you die in hell",
    question: false,
    posibilities: undefined,
  },
  {
    time: 118,
    text: "My god has shown his sympathy for all the spirits lost",
    question: false,
    posibilities: undefined,
  },
  {
    time: 129,
    text: "I'll prayed for salvation and peace for ages",
    question: false,
    posibilities: undefined,
  },
  {
    time: 133,
    text: "Standing in the summer breeze inhaling life again",
    question: false,
    posibilities: undefined,
  },
  {
    time: 139,
    text: "A new day has come",
    question: false,
    posibilities: undefined,
  },
  {
    time: 142,
    text: "A chance to relive",
    question: false,
    posibilities: undefined,
  },
  {
    time: 145,
    text: "Forget and forgive",
    question: false,
    posibilities: undefined,
  },
  {
    time: 150,
    text: "Somebody hides inside my mind",
    question: false,
    posibilities: undefined,
  },
  {
    time: 156,
    text: "We're bound _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 159,
    text: "We're bound _____",
    question: true,
    posibilities: ["TOGETHER", "ALTOGETHER", "AETHER"],
  },
  {
    time: 160,
    text: "This is my confession",
    question: false,
    posibilities: undefined,
  },
  {
    time: 163,
    text: "Soulmate or enemy",
    question: false,
    posibilities: undefined,
  },
  {
    time: 166,
    text: "A thorn in my religion",
    question: false,
    posibilities: undefined,
  },
  {
    time: 170,
    text: "Release my heart, unfold my tongue",
    question: false,
    posibilities: undefined,
  },
  {
    time: 175,
    text: "Save a _____ for me in heaven we'll meet another day",
    question: false,
    posibilities: undefined,
  },
  {
    time: 181,
    text: "Save a _____ for me in heaven we'll meet another day",
    question: true,
    posibilities: ["PLACE", "PACE", "PLAY"],
  },
  {
    time: 182,
    text: "I found forgiveness and the meaning of it all",
    question: false,
    posibilities: undefined,
  },
  {
    time: 187,
    text: "My fear is gone",
    question: false,
    posibilities: undefined,
  },
  {
    time: 189,
    text: "Gone",
    question: false,
    posibilities: undefined,
  },
  {
    time: 192,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 214,
    text: "My god has shown his sympathy for all the spirits lost",
    question: false,
    posibilities: undefined,
  },
  {
    time: 220,
    text: "I'll prayed for salvation and peace for ages",
    question: false,
    posibilities: undefined,
  },
  {
    time: 227,
    text: "Standing in the summer breeze inhaling life again",
    question: false,
    posibilities: undefined,
  },
  {
    time: 233,
    text: "A new day has come",
    question: false,
    posibilities: undefined,
  },
  {
    time: 237,
    text: "A chance to relive",
    question: false,
    posibilities: undefined,
  },
  {
    time: 240,
    text: "Forget and forgive",
    question: false,
    posibilities: undefined,
  },
  {
    time: 252,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
];

export const SheperdOfFireLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 80,
    text: "Let's take a moment and break the ice",
    question: false,
    posibilities: undefined,
  },
  {
    time: 85,
    text: "So my intentions are _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 88,
    text: "So my intentions are _____",
    question: true,
    posibilities: ["KNOWN", "NONE", "NO"],
  },
  {
    time: 89,
    text: "See I have pity in watching you suffer",
    question: false,
    posibilities: undefined,
  },
  {
    time: 92,
    text: "I know the feeling of being damned alone",
    question: false,
    posibilities: undefined,
  },
  {
    time: 97,
    text: "I got a storybook of my own",
    question: false,
    posibilities: undefined,
  },
  {
    time: 101,
    text: "Don't you see I am your pride, agent of wealth, bearer of needs",
    question: false,
    posibilities: undefined,
  },
  {
    time: 108,
    text: "(And you know it's right)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 110,
    text: "I am your war, arming the strong, aiding the _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 116,
    text: "I am your war, arming the strong, aiding the _____",
    question: true,
    posibilities: ["WEAK", "WEEK", "WEED"],
  },
  {
    time: 117,
    text: "Know me by name, Shepherd of Fire",
    question: false,
    posibilities: undefined,
  },
  {
    time: 124,
    text: "Well I can promise you paradise",
    question: false,
    posibilities: undefined,
  },
  {
    time: 128,
    text: "No need to serve on your knees",
    question: false,
    posibilities: undefined,
  },
  {
    time: 132,
    text: "And when you're _____ in the darkest of hours",
    question: false,
    posibilities: undefined,
  },
  {
    time: 135,
    text: "And when you're _____ in the darkest of hours",
    question: true,
    posibilities: ["LOST", "LOVED", "LOSS"],
  },
  {
    time: 136,
    text: "Take a moment and tell me who you see",
    question: false,
    posibilities: undefined,
  },
  {
    time: 140,
    text: "Won't tell you who not to be",
    question: false,
    posibilities: undefined,
  },
  {
    time: 145,
    text: "Now you know I am your pride, agent of wealth, bearer of needs",
    question: false,
    posibilities: undefined,
  },
  {
    time: 152,
    text: "(And you know it's right)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 153,
    text: "I am your war, arming the strong, aiding the weak",
    question: false,
    posibilities: undefined,
  },
  {
    time: 161,
    text: "Know me by name, Shepherd of Fire",
    question: false,
    posibilities: undefined,
  },
  {
    time: 170,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 219,
    text: "Disciple of the cross and champion in suffering",
    question: false,
    posibilities: undefined,
  },
  {
    time: 222,
    text: "Immerse yourself _____ the Kingdom of Redemption",
    question: false,
    posibilities: undefined,
  },
  {
    time: 225,
    text: "Immerse yourself _____ the Kingdom of Redemption",
    question: true,
    posibilities: ["INTO", "ONTO", "TO"],
  },
  {
    time: 226,
    text: "Pardon your mind from the chains of the divine",
    question: false,
    posibilities: undefined,
  },
  {
    time: 230,
    text: "Make way, the Shepherd of Fire",
    question: false,
    posibilities: undefined,
  },
  {
    time: 234,
    text: "Through the ages of time",
    question: false,
    posibilities: undefined,
  },
  {
    time: 237,
    text: "I've been known for my hate",
    question: false,
    posibilities: undefined,
  },
  {
    time: 241,
    text: "But I'm a dealer of simple choices",
    question: false,
    posibilities: undefined,
  },
  {
    time: 245,
    text: "For me its never too _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 246,
    text: "For me its never too _____",
    question: true,
    posibilities: ["LATE", "ATE", "PATE"],
  },
  {
    time: 247,
    text: "I am your pride, agent of wealth, bearer of needs",
    question: false,
    posibilities: undefined,
  },
  {
    time: 253,
    text: "(And you know it's right)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 255,
    text: "I am your war, arming the strong, aiding the weak",
    question: false,
    posibilities: undefined,
  },
  {
    time: 262,
    text: "I am your _____, I am your guilt, I am your lust!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 267,
    text: "I am your _____, I am your guilt, I am your lust!",
    question: true,
    posibilities: ["WRATH", "BRAT", "WRAP"],
  },
  {
    time: 268,
    text: "(And you know it's right)",
    question: false,
    posibilities: undefined,
  },
  {
    time: 270,
    text: "I am your law, I am your scar, I am your trust",
    question: false,
    posibilities: undefined,
  },
  {
    time: 276,
    text: "Know me by name, Shepherd of Fire",
    question: false,
    posibilities: undefined,
  },
  {
    time: 290,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
];

export const TheIslanderLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 58,
    text: "An old man by a seashore at the end of _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 62,
    text: "An old man by a seashore at the end of _____",
    question: true,
    posibilities: ["DAY", "DATE", "RAY"],
  },
  {
    time: 63,
    text: "Gazes the horizon with sea winds in his face",
    question: false,
    posibilities: undefined,
  },
  {
    time: 67,
    text: "Tempest-tossed island, seasons all the same",
    question: false,
    posibilities: undefined,
  },
  {
    time: 71,
    text: "Anchorage unpainted and a _____ without a name",
    question: false,
    posibilities: undefined,
  },
  {
    time: 78,
    text: "Anchorage unpainted and a _____ without a name",
    question: true,
    posibilities: ["SHIP", "SHEEP", "SHEET"],
  },
  {
    time: 79,
    text: "Sea without a shore for the banished one unheard",
    question: false,
    posibilities: undefined,
  },
  {
    time: 83,
    text: "He lightens the beacon, light at the end of world",
    question: false,
    posibilities: undefined,
  },
  {
    time: 88,
    text: "Showing the way, lighting hope in their hearts",
    question: false,
    posibilities: undefined,
  },
  {
    time: 92,
    text: "The ones on their travels homeward from _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 97,
    text: "The ones on their travels homeward from _____",
    question: true,
    posibilities: ["AFAR", "AFFAIR", "AS FAR"],
  },
  {
    time: 98,
    text: "This is for long-forgotten light at the end of the world",
    question: false,
    posibilities: undefined,
  },
  {
    time: 107,
    text: "Horizon crying the tears he left behind long ago",
    question: false,
    posibilities: undefined,
  },
  {
    time: 117,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 133,
    text: "The albatross is flying, making him daydream",
    question: false,
    posibilities: undefined,
  },
  {
    time: 138,
    text: "The time before he became _____ of the world's unseen",
    question: false,
    posibilities: undefined,
  },
  {
    time: 141,
    text: "The time before he became _____ of the world's unseen",
    question: true,
    posibilities: ["ONE", "WON", "ONCE"],
  },
  {
    time: 142,
    text: "Princess in the tower, children in the fields",
    question: false,
    posibilities: undefined,
  },
  {
    time: 146,
    text: "Life gave him it all, an island of the universe",
    question: false,
    posibilities: undefined,
  },
  {
    time: 154,
    text: "Now his love's a memory, a ghost in the _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 157,
    text: "Now his love's a memory, a ghost in the _____",
    question: true,
    posibilities: ["FOG", "TOG", "BOG"],
  },
  {
    time: 158,
    text: "He sets the sails one last time saying farewell to the world",
    question: false,
    posibilities: undefined,
  },
  {
    time: 162,
    text: "Anchor to the water, seabed far below",
    question: false,
    posibilities: undefined,
  },
  {
    time: 167,
    text: "Grass still in his feet and a smile beneath his _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 172,
    text: "Grass still in his feet and a smile beneath his _____",
    question: true,
    posibilities: ["BROW", "BROWN", "THROW"],
  },
  {
    time: 173,
    text: "This is for long-forgotten light at the end of the world",
    question: false,
    posibilities: undefined,
  },
  {
    time: 182,
    text: "Horizon crying the tears he left behind long ago",
    question: false,
    posibilities: undefined,
  },
  {
    time: 192,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 200,
    text: "So long ago",
    question: false,
    posibilities: undefined,
  },
  {
    time: 203,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 207,
    text: "So long ago",
    question: false,
    posibilities: undefined,
  },
  {
    time: 211,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 233,
    text: "This is for long-forgotten light at the end of the world",
    question: false,
    posibilities: undefined,
  },
  {
    time: 242,
    text: "Horizon crying the tears he left behind long ago",
    question: false,
    posibilities: undefined,
  },
  {
    time: 252,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 259,
    text: "So long ago",
    question: false,
    posibilities: undefined,
  },
  {
    time: 263,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
];

export const WarbringersLyrics: Sentence[] = [
  {
    time: 2,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 28,
    text: "Beware, beware the _____ of the Sea.",
    question: false,
    posibilities: undefined,
  },
  {
    time: 34,
    text: "Beware, beware the _____ of the Sea.",
    question: true,
    posibilities: ["DAUGHTER", "DAUNTLESS", "DOORSTEP"],
  },
  {
    time: 35,
    text: "Beware, I heard him cry",
    question: false,
    posibilities: undefined,
  },
  {
    time: 41,
    text: "His words carried upon the ocean breeze",
    question: false,
    posibilities: undefined,
  },
  {
    time: 48,
    text: "As he sank beneath the tide",
    question: false,
    posibilities: undefined,
  },
  {
    time: 55,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 58,
    text: "Those blood-soaked _____ of Kalimdor",
    question: false,
    posibilities: undefined,
  },
  {
    time: 64,
    text: "Those blood-soaked _____ of Kalimdor",
    question: true,
    posibilities: ["SHORES", "SHORTS", "SHOTS"],
  },
  {
    time: 65,
    text: "Where sailors fought and died",
    question: false,
    posibilities: undefined,
  },
  {
    time: 71,
    text: "The admiral fell at Theramore",
    question: false,
    posibilities: undefined,
  },
  {
    time: 78,
    text: "Because she left his _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 82,
    text: "Because she left his _____",
    question: true,
    posibilities: ["SIDE", "TIDE", "SIGN"],
  },
  {
    time: 83,
    text: "Why this? Why this, oh, Daughter of the Sea?",
    question: false,
    posibilities: undefined,
  },
  {
    time: 89,
    text: "Why this? Did you forget your seaside days?",
    question: false,
    posibilities: undefined,
  },
  {
    time: 95,
    text: "Always the pride of our nation's eyes",
    question: false,
    posibilities: undefined,
  },
  {
    time: 101,
    text: "How could she go astray?",
    question: false,
    posibilities: undefined,
  },
  {
    time: 110,
    text: "When she did _____ across the ocean deep",
    question: false,
    posibilities: undefined,
  },
  {
    time: 114,
    text: "When she did _____ across the ocean deep",
    question: true,
    posibilities: ["FLEE", "FLY", "FLEA"],
  },
  {
    time: 115,
    text: "The admiral followed west",
    question: false,
    posibilities: undefined,
  },
  {
    time: 121,
    text: "What else but sail to save a daughter's life",
    question: false,
    posibilities: undefined,
  },
  {
    time: 127,
    text: " And _____ she still drew breath?",
    question: false,
    posibilities: undefined,
  },
  {
    time: 132,
    text: " And _____ she still drew breath?",
    question: true,
    posibilities: ["PRAY", "PAY", "FRAME"],
  },
  {
    time: 133,
    text: "But there he found upon the distant shores",
    question: false,
    posibilities: undefined,
  },
  {
    time: 139,
    text: "Enemies 'pon the rise!",
    question: false,
    posibilities: undefined,
  },
  {
    time: 144,
    text: "But when he faced those savage foes",
    question: false,
    posibilities: undefined,
  },
  {
    time: 153,
    text: "His daughter stood aside",
    question: false,
    posibilities: undefined,
  },
  {
    time: 161,
    text: "Buried deep beneath the _____",
    question: false,
    posibilities: undefined,
  },
  {
    time: 165,
    text: "Buried deep beneath the _____",
    question: true,
    posibilities: ["WAVES", "WALES", "WASTES"],
  },
  {
    time: 166,
    text: "Betrayed by family",
    question: false,
    posibilities: undefined,
  },
  {
    time: 172,
    text: "To his nation, with his last breath, cried",
    question: false,
    posibilities: undefined,
  },
  {
    time: 178,
    text: "Beware the Daughter of the Sea.",
    question: false,
    posibilities: undefined,
  },
  {
    time: 185,
    text: "*Music*",
    question: false,
    posibilities: undefined,
  },
  {
    time: 235,
    text: "I heard, I heard across the _____ sea",
    question: false,
    posibilities: undefined,
  },
  {
    time: 240,
    text: "I heard, I heard across the _____ sea",
    question: true,
    posibilities: ["MOONLIT", "MOONLIGHT", "MOONBEAM"],
  },
  {
    time: 241,
    text: "The old voice warning me",
    question: false,
    posibilities: undefined,
  },
  {
    time: 247,
    text: "Beware, beware the Daughter of the Sea",
    question: false,
    posibilities: undefined,
  },
  {
    time: 254,
    text: "Beware, beware of me",
    question: false,
    posibilities: undefined,
  },
];

export default Sentence;
